image: ubuntu:20.04

pipelines:
  branches:
    '{dev}':
        - step:
            caches:
              - maven
            script: 
              - apt-get update
              - apt-get install -y maven 
              - apt-get install -y amazon-ecr-credential-helper
              - apt-get update && apt-get install -y python3-pip
              - pip3 install -U awscli
              - $(aws ecr get-login --no-include-email --region us-west-2)
              - mvn compile jib:build
              - aws ecs update-service --region us-west-2 --cluster sluber --service backend --force-new-deployment

  default:
    - step:
        caches:
          - maven
        script: 
          - apt-get update
          - apt-get install -y maven 
          - mvn -B verify # -B batch mode makes Maven less verbose