image: ubuntu:20.04

pipelines:
  branches:
    '{dev}':
        - step:
            caches:
              - maven
            script: 
              - apt-get update
              - apt-get install -y maven 
              - apt-get install -y amazon-ecr-credential-helper
              - mvn compile jib:build    
  default:
    - step:
        caches:
          - maven
        script: 
          - apt-get update
          - apt-get install -y maven 
          - mvn -B verify # -B batch mode makes Maven less verbose