swagger: '2.0'
info:
  version: 1.0.0
  title: Slalom SLUBER
paths:
  /sluber/drivers:
    post:
      tags:
        - drivers
      summary: Create a new driver
      operationId: createDriver
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Driver to create
          required: true
          schema:
            $ref: '#/definitions/DriverDetails'
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/DriverResponse'
        400:
          description: Invalid input
definitions:
  DriverDetails:
    type: object
    properties:
      name:
        type: string
  DriverResponse:
    type: object
    properties:
      driverId:
        type: string
schemes:
  - http