swagger: '2.0'
info:
  version: 1.0.0
  title: Slalom SLUBER
  description: 'SLUBER backend service to help persons coordinate rides'
paths:
  /sluber/trips:
    post:
      tags:
        - trip
      summary: Create a new trip
      operationId: createTrip
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Trip to create
          required: true
          schema:
            $ref: '#/definitions/CreateTripDetails'
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/TripDetails'
        400:
          description: Invalid input
    get:
      tags:
        - trip
      summary: Retrieves all trips
      operationId: getTrips
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/TripDetails'
definitions:
  CreateTripDetails:
    type: object
    properties:
      origin:
        type: string
  TripDetails:
    type: object
    properties:
      tripId:
        type: string
      origin:
        type: string
      departureTime:
        type: string
        # format: date-time
      comments:
        type: string
      seatsAvailable:
        type: integer
      passengers:
        type: array
        items:
          $ref: '#/definitions/EmployeeDetails'
  EmployeeDetails:
    type: object
    properties:
      name:
        type: string
      phoneNumber:
        type: string

schemes:
  - http